"""initial schema

Revision ID: b9e8031ebc51
Revises: 
Create Date: 2026-09-12 10:59:58.247532+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'b9e8031ebc51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'moderator', 'admin', name='user_role'), server_default='citizen', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('citizen_profiles',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.Enum('mr', 'hi', 'en', name='citizen_preferred_language'), nullable=True),
    sa.Column('notifications_opt_in', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('issues',
    sa.Column('tracking_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('pothole', 'garbage', 'streetlight', 'water_leakage', 'damaged_road', 'open_manhole', 'fallen_tree', 'road_obstruction', 'drainage', 'public_cleanliness', 'accessibility', 'other', name='issue_category'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='issue_severity'), nullable=False),
    sa.Column('status', sa.Enum('reported', 'ai_analyzed', 'verified', 'under_review', 'work_started', 'resolved', 'citizen_verified', 'reopened', name='issue_status'), server_default='reported', nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('location_importance', sa.Float(), server_default='0.6', nullable=False),
    sa.Column('language', sa.Enum('mr', 'hi', 'en', name='issue_language'), nullable=True),
    sa.Column('voice_transcript', sa.Text(), nullable=True),
    sa.Column('reporter_id', app.db.types.GUID(), nullable=True),
    sa.Column('reporter_display_name', sa.String(length=120), nullable=True),
    sa.Column('reporter_contact', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_escalated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('people_affected_estimate', sa.Integer(), server_default='1', nullable=False),
    sa.Column('grouped_report_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('duplicate_of_id', app.db.types.GUID(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_category'), 'issues', ['category'], unique=False)
    op.create_index(op.f('ix_issues_duplicate_of_id'), 'issues', ['duplicate_of_id'], unique=False)
    op.create_index(op.f('ix_issues_lat'), 'issues', ['lat'], unique=False)
    op.create_index(op.f('ix_issues_lng'), 'issues', ['lng'], unique=False)
    op.create_index(op.f('ix_issues_reported_at'), 'issues', ['reported_at'], unique=False)
    op.create_index(op.f('ix_issues_reporter_id'), 'issues', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_issues_severity'), 'issues', ['severity'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_tracking_id'), 'issues', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_issues_ward'), 'issues', ['ward'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('issue_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_issue_id'), 'follow_ups', ['issue_id'], unique=False)
    op.create_table('issue_ai_analyses',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('detected_category', sa.Enum('pothole', 'garbage', 'streetlight', 'water_leakage', 'damaged_road', 'open_manhole', 'fallen_tree', 'road_obstruction', 'drainage', 'public_cleanliness', 'accessibility', 'other', name='ai_detected_category'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='ai_analysis_severity'), nullable=False),
    sa.Column('safety_risk', sa.Enum('low', 'medium', 'high', 'critical', name='ai_analysis_safety_risk'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('possible_causes', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_ai_analyses_issue_id'), 'issue_ai_analyses', ['issue_id'], unique=False)
    op.create_table('issue_comments',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('author_id', app.db.types.GUID(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    op.create_table('issue_confirmations',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('confirmer_id', app.db.types.GUID(), nullable=True),
    sa.Column('confirmer_display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['confirmer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_confirmations_created_at'), 'issue_confirmations', ['created_at'], unique=False)
    op.create_index(op.f('ix_issue_confirmations_issue_id'), 'issue_confirmations', ['issue_id'], unique=False)
    op.create_table('issue_duplicates',
    sa.Column('primary_issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('duplicate_issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duplicate_issue_id', name='uq_issue_duplicate_child')
    )
    op.create_index(op.f('ix_issue_duplicates_duplicate_issue_id'), 'issue_duplicates', ['duplicate_issue_id'], unique=False)
    op.create_index(op.f('ix_issue_duplicates_primary_issue_id'), 'issue_duplicates', ['primary_issue_id'], unique=False)
    op.create_table('issue_images',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('kind', sa.Enum('report', 'before', 'after', name='issue_image_kind'), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_images_issue_id'), 'issue_images', ['issue_id'], unique=False)
    op.create_table('issue_resolutions',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('before_image_url', sa.String(length=2048), nullable=True),
    sa.Column('after_image_url', sa.String(length=2048), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_label', sa.String(length=120), nullable=True),
    sa.Column('resolved_by_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_resolutions_issue_id'), 'issue_resolutions', ['issue_id'], unique=False)
    op.create_table('issue_status_history',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('reported', 'ai_analyzed', 'verified', 'under_review', 'work_started', 'resolved', 'citizen_verified', 'reopened', name='status_history_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.Enum('system', 'ai', 'citizen', 'authority', name='status_history_actor'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_status_history_created_at'), 'issue_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_issue_status_history_issue_id'), 'issue_status_history', ['issue_id'], unique=False)
    op.create_table('issue_verifications',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('verifier_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_verifications_issue_id'), 'issue_verifications', ['issue_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('role_target', sa.Enum('citizen', 'moderator', 'admin', name='notification_role_target'), nullable=True),
    sa.Column('issue_id', app.db.types.GUID(), nullable=True),
    sa.Column('type', sa.Enum('follow_up', 'escalation', 'status_change', 'system', name='notification_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_issue_id'), 'notifications', ['issue_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('priority_scores',
    sa.Column('issue_id', app.db.types.GUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_scores_issue_id'), 'priority_scores', ['issue_id'], unique=False)
    op.create_table('ai_conversation_messages',
    sa.Column('conversation_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='ai_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_messages_conversation_id'), 'ai_conversation_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_conversation_messages_conversation_id'), table_name='ai_conversation_messages')
    op.drop_table('ai_conversation_messages')
    op.drop_index(op.f('ix_priority_scores_issue_id'), table_name='priority_scores')
    op.drop_table('priority_scores')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_issue_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_issue_verifications_issue_id'), table_name='issue_verifications')
    op.drop_table('issue_verifications')
    op.drop_index(op.f('ix_issue_status_history_issue_id'), table_name='issue_status_history')
    op.drop_index(op.f('ix_issue_status_history_created_at'), table_name='issue_status_history')
    op.drop_table('issue_status_history')
    op.drop_index(op.f('ix_issue_resolutions_issue_id'), table_name='issue_resolutions')
    op.drop_table('issue_resolutions')
    op.drop_index(op.f('ix_issue_images_issue_id'), table_name='issue_images')
    op.drop_table('issue_images')
    op.drop_index(op.f('ix_issue_duplicates_primary_issue_id'), table_name='issue_duplicates')
    op.drop_index(op.f('ix_issue_duplicates_duplicate_issue_id'), table_name='issue_duplicates')
    op.drop_table('issue_duplicates')
    op.drop_index(op.f('ix_issue_confirmations_issue_id'), table_name='issue_confirmations')
    op.drop_index(op.f('ix_issue_confirmations_created_at'), table_name='issue_confirmations')
    op.drop_table('issue_confirmations')
    op.drop_index(op.f('ix_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_table('issue_comments')
    op.drop_index(op.f('ix_issue_ai_analyses_issue_id'), table_name='issue_ai_analyses')
    op.drop_table('issue_ai_analyses')
    op.drop_index(op.f('ix_follow_ups_issue_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_issues_ward'), table_name='issues')
    op.drop_index(op.f('ix_issues_tracking_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_severity'), table_name='issues')
    op.drop_index(op.f('ix_issues_reporter_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_reported_at'), table_name='issues')
    op.drop_index(op.f('ix_issues_lng'), table_name='issues')
    op.drop_index(op.f('ix_issues_lat'), table_name='issues')
    op.drop_index(op.f('ix_issues_duplicate_of_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_category'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('citizen_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
